# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: store.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'store.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bstore.proto\x12\x05model\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1egoogle/protobuf/wrappers.proto\"%\n\x06Stores\x12\x1b\n\x05store\x18\x01 \x03(\x0b\x32\x0c.model.Store\"x\n\x05Store\x12\x0f\n\x07idStore\x18\x01 \x01(\x05\x12\x11\n\tstoreName\x18\x02 \x01(\t\x12\x0c\n\x04\x63ode\x18\x03 \x01(\t\x12\x0f\n\x07\x61\x64\x64ress\x18\x04 \x01(\t\x12\x0c\n\x04\x63ity\x18\x05 \x01(\t\x12\r\n\x05state\x18\x06 \x01(\t\x12\x0f\n\x07\x65nabled\x18\x07 \x01(\x08\x32\x97\x01\n\x0cStoreService\x12(\n\x08GetStore\x12\x0c.model.Store\x1a\x0c.model.Store\"\x00\x12\x32\n\x07\x46indAll\x12\x16.google.protobuf.Empty\x1a\r.model.Stores\"\x00\x12)\n\tSaveStore\x12\x0c.model.Store\x1a\x0c.model.Store\"\x00\x42\"\n\x14\x63om.stockearte.modelB\nStoreProtob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'store_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\024com.stockearte.modelB\nStoreProto'
  _globals['_STORES']._serialized_start=83
  _globals['_STORES']._serialized_end=120
  _globals['_STORE']._serialized_start=122
  _globals['_STORE']._serialized_end=242
  _globals['_STORESERVICE']._serialized_start=245
  _globals['_STORESERVICE']._serialized_end=396
# @@protoc_insertion_point(module_scope)
