CREATE TABLE `rol` (
  `id_rol` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `rol` VARCHAR(255) DEFAULT NULL,
  `enabled` BOOLEAN DEFAULT TRUE,

  PRIMARY KEY (`id_rol`)
) ENGINE=INNODB DEFAULT CHARSET=utf8

CREATE TABLE `user` (
  `id_user` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(255) DEFAULT NULL,
  `name` VARCHAR(255) DEFAULT NULL,
  `lastname` VARCHAR(255) DEFAULT NULL,
   `password` VARCHAR(255) DEFAULT NULL,
  `enabled` BOOLEAN DEFAULT TRUE,
  `id_rol` INT(11) UNSIGNED DEFAULT NULL,
  `id_store` INT(11) UNSIGNED DEFAULT NULL,
  PRIMARY KEY (`id_user`)
) ENGINE=INNODB DEFAULT CHARSET=utf8

CREATE TABLE `store` (
  `id_store` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `store` VARCHAR(255) DEFAULT NULL,
  `code` VARCHAR(255) DEFAULT NULL,
  `address` VARCHAR(255) DEFAULT NULL,
  `city` VARCHAR(255) DEFAULT NULL,
  `state` VARCHAR(255) DEFAULT NULL,
  `enabled` BOOLEAN DEFAULT TRUE,

  PRIMARY KEY (`id_store`)
) ENGINE=INNODB DEFAULT CHARSET=utf8


CREATE TABLE `product` (
  `id_product` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `product` VARCHAR(255) DEFAULT NULL,
  `code` VARCHAR(10) DEFAULT NULL,
  `img` VARCHAR(255) DEFAULT NULL,
   `enabled` BOOLEAN DEFAULT TRUE,

  PRIMARY KEY (`id_product`)
) ENGINE=INNODB DEFAULT CHARSET=utf8

CREATE TABLE `product_size` (
  `id_product_size` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_product`INT(11) UNSIGNED NOT NULL,
  `size` VARCHAR(255) DEFAULT NULL,
     `enabled` BOOLEAN DEFAULT TRUE,
  PRIMARY KEY (`id_product_size`)
) ENGINE=INNODB DEFAULT CHARSET=utf8

CREATE TABLE `product_color` (
  `id_product_color` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_product`INT(11) UNSIGNED NOT NULL,
  `color` VARCHAR(255) DEFAULT NULL,
     `enabled` BOOLEAN DEFAULT TRUE,
  PRIMARY KEY (`id_product_color`)
) ENGINE=INNODB DEFAULT CHARSET=utf8

CREATE TABLE `product_stock` (
`id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_product` INT(11) UNSIGNED NOT NULL,
  `id_store` INT(11) UNSIGNED NOT NULL,
  `id_product_color`INT(11) UNSIGNED NOT NULL,
   `id_product_size`INT(11) UNSIGNED NOT NULL,
  `stock` INT(11) DEFAULT NULL,
   PRIMARY KEY (`id`)
) ENGINE=INNODB DEFAULT CHARSET=utf8

CREATE TABLE `product_store` (
`id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_product` INT(11) UNSIGNED NOT NULL,
  `id_product_store`INT(11) UNSIGNED NOT NULL,
   PRIMARY KEY (`id`)
) ENGINE=INNODB DEFAULT CHARSET=utf8
