# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: dispatchOrder.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'dispatchOrder.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x64ispatchOrder.proto\x12\x05model\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1egoogle/protobuf/wrappers.proto\"`\n\rDispatchOrder\x12\x17\n\x0fidDispatchOrder\x18\x01 \x01(\x05\x12\x17\n\x0fidPurchaseOrder\x18\x02 \x01(\x05\x12\x1d\n\x15\x65stimatedShippingDate\x18\x03 \x01(\t2Y\n\x14\x44ispatchOrderService\x12\x41\n\x11SaveDispatchOrder\x12\x14.model.DispatchOrder\x1a\x14.model.DispatchOrder\"\x00\x42*\n\x14\x63om.stockearte.modelB\x12\x44ispatchOrderProtob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dispatchOrder_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\024com.stockearte.modelB\022DispatchOrderProto'
  _globals['_DISPATCHORDER']._serialized_start=91
  _globals['_DISPATCHORDER']._serialized_end=187
  _globals['_DISPATCHORDERSERVICE']._serialized_start=189
  _globals['_DISPATCHORDERSERVICE']._serialized_end=278
# @@protoc_insertion_point(module_scope)
