# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import dispatchOrder_pb2 as dispatchOrder__pb2

GRPC_GENERATED_VERSION = '1.66.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in dispatchOrder_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DispatchOrderServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SaveDispatchOrder = channel.unary_unary(
                '/model.DispatchOrderService/SaveDispatchOrder',
                request_serializer=dispatchOrder__pb2.DispatchOrder.SerializeToString,
                response_deserializer=dispatchOrder__pb2.DispatchOrder.FromString,
                _registered_method=True)


class DispatchOrderServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SaveDispatchOrder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DispatchOrderServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SaveDispatchOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.SaveDispatchOrder,
                    request_deserializer=dispatchOrder__pb2.DispatchOrder.FromString,
                    response_serializer=dispatchOrder__pb2.DispatchOrder.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'model.DispatchOrderService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('model.DispatchOrderService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DispatchOrderService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SaveDispatchOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/model.DispatchOrderService/SaveDispatchOrder',
            dispatchOrder__pb2.DispatchOrder.SerializeToString,
            dispatchOrder__pb2.DispatchOrder.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
