# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: orderItem.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'orderItem.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2
import purchaseOrder_pb2 as purchaseOrder__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0forderItem.proto\x12\x05model\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x13purchaseOrder.proto\"1\n\nOrderItems\x12#\n\torderItem\x18\x01 \x03(\x0b\x32\x10.model.OrderItem\"\xa6\x01\n\tOrderItem\x12\x13\n\x0bidOrderItem\x18\x01 \x01(\x05\x12\x13\n\x0bproductCode\x18\x02 \x01(\t\x12\r\n\x05\x63olor\x18\x03 \x01(\t\x12\x0c\n\x04size\x18\x04 \x01(\t\x12\x17\n\x0frequestedAmount\x18\x05 \x01(\x05\x12+\n\rpurchaseOrder\x18\x06 \x01(\x0b\x32\x14.model.PurchaseOrder\x12\x0c\n\x04send\x18\x07 \x01(\x08\x32I\n\x10OrderItemService\x12\x35\n\rSaveOrderItem\x12\x10.model.OrderItem\x1a\x10.model.OrderItem\"\x00\x42&\n\x14\x63om.stockearte.modelB\x0eOrderItemProtob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'orderItem_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\024com.stockearte.modelB\016OrderItemProto'
  _globals['_ORDERITEMS']._serialized_start=108
  _globals['_ORDERITEMS']._serialized_end=157
  _globals['_ORDERITEM']._serialized_start=160
  _globals['_ORDERITEM']._serialized_end=326
  _globals['_ORDERITEMSERVICE']._serialized_start=328
  _globals['_ORDERITEMSERVICE']._serialized_end=401
# @@protoc_insertion_point(module_scope)
