# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: productStock.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'productStock.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2
import store_pb2 as store__pb2
import product_pb2 as product__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12productStock.proto\x12\x05model\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x0bstore.proto\x1a\rproduct.proto\":\n\rProductsStock\x12)\n\x0cproductStock\x18\x01 \x03(\x0b\x32\x13.model.ProductStock\"<\n\x16ProductAndStoreRequest\x12\x11\n\tidProduct\x18\x01 \x01(\x05\x12\x0f\n\x07idStore\x18\x02 \x01(\x05\"s\n\x0cProductStock\x12\x16\n\x0eidProductStock\x18\x01 \x01(\x05\x12\r\n\x05stock\x18\x02 \x01(\x05\x12\x1f\n\x07product\x18\x03 \x01(\x0b\x32\x0e.model.Product\x12\x1b\n\x05store\x18\x04 \x01(\x0b\x32\x0c.model.Store2\xe7\x01\n\x13ProductStockService\x12=\n\x0fGetProductStock\x12\x13.model.ProductStock\x1a\x13.model.ProductStock\"\x00\x12Q\n\x19GetStockByProductAndStore\x12\x1d.model.ProductAndStoreRequest\x1a\x13.model.ProductStock\"\x00\x12>\n\x10SaveProductStock\x12\x13.model.ProductStock\x1a\x13.model.ProductStock\"\x00\x42)\n\x14\x63om.stockearte.modelB\x11ProductStockProtob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'productStock_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\024com.stockearte.modelB\021ProductStockProto'
  _globals['_PRODUCTSSTOCK']._serialized_start=118
  _globals['_PRODUCTSSTOCK']._serialized_end=176
  _globals['_PRODUCTANDSTOREREQUEST']._serialized_start=178
  _globals['_PRODUCTANDSTOREREQUEST']._serialized_end=238
  _globals['_PRODUCTSTOCK']._serialized_start=240
  _globals['_PRODUCTSTOCK']._serialized_end=355
  _globals['_PRODUCTSTOCKSERVICE']._serialized_start=358
  _globals['_PRODUCTSTOCKSERVICE']._serialized_end=589
# @@protoc_insertion_point(module_scope)
