# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import productStock_pb2 as productStock__pb2

GRPC_GENERATED_VERSION = '1.66.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in productStock_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ProductStockServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetProductStock = channel.unary_unary(
                '/model.ProductStockService/GetProductStock',
                request_serializer=productStock__pb2.ProductStock.SerializeToString,
                response_deserializer=productStock__pb2.ProductStock.FromString,
                _registered_method=True)
        self.GetStockByProductAndStore = channel.unary_unary(
                '/model.ProductStockService/GetStockByProductAndStore',
                request_serializer=productStock__pb2.ProductAndStoreRequest.SerializeToString,
                response_deserializer=productStock__pb2.ProductStock.FromString,
                _registered_method=True)
        self.SaveProductStock = channel.unary_unary(
                '/model.ProductStockService/SaveProductStock',
                request_serializer=productStock__pb2.ProductStock.SerializeToString,
                response_deserializer=productStock__pb2.ProductStock.FromString,
                _registered_method=True)


class ProductStockServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetProductStock(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStockByProductAndStore(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SaveProductStock(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ProductStockServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetProductStock': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProductStock,
                    request_deserializer=productStock__pb2.ProductStock.FromString,
                    response_serializer=productStock__pb2.ProductStock.SerializeToString,
            ),
            'GetStockByProductAndStore': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStockByProductAndStore,
                    request_deserializer=productStock__pb2.ProductAndStoreRequest.FromString,
                    response_serializer=productStock__pb2.ProductStock.SerializeToString,
            ),
            'SaveProductStock': grpc.unary_unary_rpc_method_handler(
                    servicer.SaveProductStock,
                    request_deserializer=productStock__pb2.ProductStock.FromString,
                    response_serializer=productStock__pb2.ProductStock.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'model.ProductStockService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('model.ProductStockService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ProductStockService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetProductStock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/model.ProductStockService/GetProductStock',
            productStock__pb2.ProductStock.SerializeToString,
            productStock__pb2.ProductStock.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStockByProductAndStore(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/model.ProductStockService/GetStockByProductAndStore',
            productStock__pb2.ProductAndStoreRequest.SerializeToString,
            productStock__pb2.ProductStock.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SaveProductStock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/model.ProductStockService/SaveProductStock',
            productStock__pb2.ProductStock.SerializeToString,
            productStock__pb2.ProductStock.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
