# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
import purchaseOrder_pb2 as purchaseOrder__pb2

GRPC_GENERATED_VERSION = '1.66.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in purchaseOrder_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PurchaseOrderServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetPurchaseOrder = channel.unary_unary(
                '/model.PurchaseOrderService/GetPurchaseOrder',
                request_serializer=purchaseOrder__pb2.PurchaseOrder.SerializeToString,
                response_deserializer=purchaseOrder__pb2.PurchaseOrderWithItem.FromString,
                _registered_method=True)
        self.FindAll = channel.unary_unary(
                '/model.PurchaseOrderService/FindAll',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=purchaseOrder__pb2.PurchaseOrders.FromString,
                _registered_method=True)
        self.AddPurchaseOrder = channel.unary_unary(
                '/model.PurchaseOrderService/AddPurchaseOrder',
                request_serializer=purchaseOrder__pb2.PurchaseOrder.SerializeToString,
                response_deserializer=purchaseOrder__pb2.PurchaseOrder.FromString,
                _registered_method=True)
        self.FindAllByStore = channel.unary_unary(
                '/model.PurchaseOrderService/FindAllByStore',
                request_serializer=purchaseOrder__pb2.PurchaseAndStoreRequest.SerializeToString,
                response_deserializer=purchaseOrder__pb2.PurchaseOrders.FromString,
                _registered_method=True)
        self.FindAllByStoreAndState = channel.unary_unary(
                '/model.PurchaseOrderService/FindAllByStoreAndState',
                request_serializer=purchaseOrder__pb2.PurchaseAndStoreRequest.SerializeToString,
                response_deserializer=purchaseOrder__pb2.PurchaseOrders.FromString,
                _registered_method=True)


class PurchaseOrderServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetPurchaseOrder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FindAll(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddPurchaseOrder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FindAllByStore(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FindAllByStoreAndState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PurchaseOrderServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetPurchaseOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPurchaseOrder,
                    request_deserializer=purchaseOrder__pb2.PurchaseOrder.FromString,
                    response_serializer=purchaseOrder__pb2.PurchaseOrderWithItem.SerializeToString,
            ),
            'FindAll': grpc.unary_unary_rpc_method_handler(
                    servicer.FindAll,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=purchaseOrder__pb2.PurchaseOrders.SerializeToString,
            ),
            'AddPurchaseOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.AddPurchaseOrder,
                    request_deserializer=purchaseOrder__pb2.PurchaseOrder.FromString,
                    response_serializer=purchaseOrder__pb2.PurchaseOrder.SerializeToString,
            ),
            'FindAllByStore': grpc.unary_unary_rpc_method_handler(
                    servicer.FindAllByStore,
                    request_deserializer=purchaseOrder__pb2.PurchaseAndStoreRequest.FromString,
                    response_serializer=purchaseOrder__pb2.PurchaseOrders.SerializeToString,
            ),
            'FindAllByStoreAndState': grpc.unary_unary_rpc_method_handler(
                    servicer.FindAllByStoreAndState,
                    request_deserializer=purchaseOrder__pb2.PurchaseAndStoreRequest.FromString,
                    response_serializer=purchaseOrder__pb2.PurchaseOrders.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'model.PurchaseOrderService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('model.PurchaseOrderService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PurchaseOrderService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetPurchaseOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/model.PurchaseOrderService/GetPurchaseOrder',
            purchaseOrder__pb2.PurchaseOrder.SerializeToString,
            purchaseOrder__pb2.PurchaseOrderWithItem.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FindAll(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/model.PurchaseOrderService/FindAll',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            purchaseOrder__pb2.PurchaseOrders.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddPurchaseOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/model.PurchaseOrderService/AddPurchaseOrder',
            purchaseOrder__pb2.PurchaseOrder.SerializeToString,
            purchaseOrder__pb2.PurchaseOrder.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FindAllByStore(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/model.PurchaseOrderService/FindAllByStore',
            purchaseOrder__pb2.PurchaseAndStoreRequest.SerializeToString,
            purchaseOrder__pb2.PurchaseOrders.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FindAllByStoreAndState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/model.PurchaseOrderService/FindAllByStoreAndState',
            purchaseOrder__pb2.PurchaseAndStoreRequest.SerializeToString,
            purchaseOrder__pb2.PurchaseOrders.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
