# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: user.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'user.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nuser.proto\x12\x05model\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1egoogle/protobuf/wrappers.proto\"\"\n\x05Users\x12\x19\n\x04user\x18\x01 \x03(\x0b\x32\x0b.model.User\"\x8a\x01\n\x04User\x12\x0e\n\x06idUser\x18\x01 \x01(\x05\x12\x10\n\x08username\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x10\n\x08lastname\x18\x04 \x01(\t\x12\x10\n\x08password\x18\x05 \x01(\t\x12\x0c\n\x04role\x18\x06 \x01(\t\x12\x0f\n\x07idStore\x18\x07 \x01(\x05\x12\x0f\n\x07\x65nabled\x18\x08 \x01(\x08\x32\xbb\x01\n\x0cUsersService\x12*\n\x0cValidateUser\x12\x0b.model.User\x1a\x0b.model.User\"\x00\x12%\n\x07GetUser\x12\x0b.model.User\x1a\x0b.model.User\"\x00\x12\x31\n\x07\x46indAll\x12\x16.google.protobuf.Empty\x1a\x0c.model.Users\"\x00\x12%\n\x07\x41\x64\x64User\x12\x0b.model.User\x1a\x0b.model.User\"\x00\x42!\n\x14\x63om.stockearte.modelB\tUserProtob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'user_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\024com.stockearte.modelB\tUserProto'
  _globals['_USERS']._serialized_start=82
  _globals['_USERS']._serialized_end=116
  _globals['_USER']._serialized_start=119
  _globals['_USER']._serialized_end=257
  _globals['_USERSSERVICE']._serialized_start=260
  _globals['_USERSSERVICE']._serialized_end=447
# @@protoc_insertion_point(module_scope)
