# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
import product_pb2 as product__pb2

GRPC_GENERATED_VERSION = '1.66.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in product_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ProductServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetProduct = channel.unary_unary(
                '/model.ProductService/GetProduct',
                request_serializer=product__pb2.Product.SerializeToString,
                response_deserializer=product__pb2.Product.FromString,
                _registered_method=True)
        self.FindAll = channel.unary_unary(
                '/model.ProductService/FindAll',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=product__pb2.Products.FromString,
                _registered_method=True)
        self.SaveProduct = channel.unary_unary(
                '/model.ProductService/SaveProduct',
                request_serializer=product__pb2.Product.SerializeToString,
                response_deserializer=product__pb2.Product.FromString,
                _registered_method=True)
        self.FindProductsByStore = channel.unary_unary(
                '/model.ProductService/FindProductsByStore',
                request_serializer=product__pb2.StoreRequest.SerializeToString,
                response_deserializer=product__pb2.Products.FromString,
                _registered_method=True)
        self.FindProductByCode = channel.unary_unary(
                '/model.ProductService/FindProductByCode',
                request_serializer=product__pb2.ProductCodeRequest.SerializeToString,
                response_deserializer=product__pb2.Product.FromString,
                _registered_method=True)


class ProductServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetProduct(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FindAll(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SaveProduct(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FindProductsByStore(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FindProductByCode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ProductServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetProduct': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProduct,
                    request_deserializer=product__pb2.Product.FromString,
                    response_serializer=product__pb2.Product.SerializeToString,
            ),
            'FindAll': grpc.unary_unary_rpc_method_handler(
                    servicer.FindAll,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=product__pb2.Products.SerializeToString,
            ),
            'SaveProduct': grpc.unary_unary_rpc_method_handler(
                    servicer.SaveProduct,
                    request_deserializer=product__pb2.Product.FromString,
                    response_serializer=product__pb2.Product.SerializeToString,
            ),
            'FindProductsByStore': grpc.unary_unary_rpc_method_handler(
                    servicer.FindProductsByStore,
                    request_deserializer=product__pb2.StoreRequest.FromString,
                    response_serializer=product__pb2.Products.SerializeToString,
            ),
            'FindProductByCode': grpc.unary_unary_rpc_method_handler(
                    servicer.FindProductByCode,
                    request_deserializer=product__pb2.ProductCodeRequest.FromString,
                    response_serializer=product__pb2.Product.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'model.ProductService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('model.ProductService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ProductService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetProduct(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/model.ProductService/GetProduct',
            product__pb2.Product.SerializeToString,
            product__pb2.Product.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FindAll(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/model.ProductService/FindAll',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            product__pb2.Products.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SaveProduct(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/model.ProductService/SaveProduct',
            product__pb2.Product.SerializeToString,
            product__pb2.Product.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FindProductsByStore(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/model.ProductService/FindProductsByStore',
            product__pb2.StoreRequest.SerializeToString,
            product__pb2.Products.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FindProductByCode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/model.ProductService/FindProductByCode',
            product__pb2.ProductCodeRequest.SerializeToString,
            product__pb2.Product.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
