# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: role.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'role.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nrole.proto\x12\x05model\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1egoogle/protobuf/wrappers.proto\"\"\n\x05Roles\x12\x19\n\x04role\x18\x01 \x03(\x0b\x32\x0b.model.Role\"(\n\x04Role\x12\x0e\n\x06idRole\x18\x01 \x01(\x05\x12\x10\n\x08roleName\x18\x02 \x01(\t2@\n\x0bRoleService\x12\x31\n\x07\x46indAll\x12\x16.google.protobuf.Empty\x1a\x0c.model.Roles\"\x00\x42!\n\x14\x63om.stockearte.modelB\tRoleProtob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'role_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\024com.stockearte.modelB\tRoleProto'
  _globals['_ROLES']._serialized_start=82
  _globals['_ROLES']._serialized_end=116
  _globals['_ROLE']._serialized_start=118
  _globals['_ROLE']._serialized_end=158
  _globals['_ROLESERVICE']._serialized_start=160
  _globals['_ROLESERVICE']._serialized_end=224
# @@protoc_insertion_point(module_scope)
